org.gradle.jvmargs=-Xmx1400m -Dfile.encoding=UTF-8 -XX:+UseSerialGC -XX:MaxMetaspaceSize=384m
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false
kotlin.caching.enabled=false
android.enableR8.fullMode=false
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx512m,-XX:MaxMetaspaceSize=256m
kotlin.incremental=false
